--- # Outline to playbook translation
- hosts: demo
  user: ansible1
  sudo: yes
  connection: ssh
  gather_facts: no

  tasks:
    - name: date/time stamp for playbook start 
      raw: /usr/bin/date > /home/ansible1/playbooks/playbook_start.log
    - name: install the apache web server
      yum: pkg=httpd state=latest
      notify: restart the HTTPD
    - name: install client software - telnet
      yum: pkg=telnet state=latest
    - name: log all the insatllled packages
      raw: yum list installed > /home/ansible1/playbooks/installed.log
    - name: date/time stamp for playbook end
      raw: /usr/bin/date > /home/ansible1/playbooks/palybook_end.log
      
  handlers:
    - name: restart the HTTPD # This has to match the notify name#
      action: service name=httpd state=restarted

